[package]
name = "macroquad-profiler"
version = "0.1.2"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"
description = "Profiler UI for macroquad"
license = "MIT/Apache-2.0"

[dependencies]
macroquad = { path = "../", version = "0.3" }
